#!/usr/bin/env python3
"""Validate the PDF fixtures generated by the native iOS and Android tests."""
import argparse
import json
import re
import unicodedata
from pathlib import Path

from pypdf import PdfReader


def compact(text):
    return re.sub(r"\s+", "", unicodedata.normalize("NFKC", text))


def inspect(path):
    document = PdfReader(path)
    pages = [compact(page.extract_text() or "") for page in document.pages]
    text = "".join(pages)
    errors = []
    for number in range(1, 46):
        if text.count(f"Parágrafo{number}.") != 3:
            errors.append(f"Paragraph {number}: missing or duplicated content")
    for marker, expected in {
        "01/06/2026": 135,
        "quantidade1234.": 135,
        "FIMLEITURA": 1,
        "COMENTARIOINTEGRAL": 1,
        "578NOTAINTEGRAL": 1,
        "579SEGUNDANOTAINTEGRAL": 1,
        "Pessoadeteste": 1,
    }.items():
        actual = text.count(marker)
        if actual != expected:
            errors.append(f"{marker}: expected {expected}, got {actual}")
    positions = {marker: [i + 1 for i, page in enumerate(pages) if marker in page]
                 for marker in ["FIMLEITURA", "578NOTAINTEGRAL", "579SEGUNDANOTAINTEGRAL", "COMENTARIOINTEGRAL"]}
    if all(positions.values()):
        if positions["COMENTARIOINTEGRAL"][0] <= max(positions["FIMLEITURA"][0], positions["579SEGUNDANOTAINTEGRAL"][0]):
            errors.append("Comment must start on a separate page after all reading and notes")
    if "01dejunho" not in pages[0] or "1diaselecionado" not in pages[0]:
        errors.append("Incomplete cover date or incorrect singular selection label")
    for number, page in enumerate(document.pages, 1):
        if abs(float(page.mediabox.width) - 595) > 1 or abs(float(page.mediabox.height) - 842) > 1:
            errors.append(f"Page {number}: unexpected paper dimensions")
    return {"file": str(path.resolve()), "pages": len(pages), "markers": positions,
            "errors": errors, "passed": not errors}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ios", type=Path, required=True)
    parser.add_argument("--android", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    report = {"ios": inspect(args.ios), "android": inspect(args.android),
              "scope": "Fixture content, dates, ordering and paper size. Visual inspection remains required; not an all-export certification."}
    args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    for platform in ("ios", "android"):
        result = report[platform]
        print(f"{platform}: {result['pages']} pages, {len(result['errors'])} errors")
        for error in result["errors"]:
            print(f"  {error}")
    return int(any(not report[platform]["passed"] for platform in ("ios", "android")))


if __name__ == "__main__":
    raise SystemExit(main())
